version: "3.9"

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_ui
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/workspace
    working_dir: /workspace
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - AGRAPH_HOST=ag1jdz6nqkhfjj72.allegrograph.cloud
      - AGRAPH_PORT=10035
      - AGRAPH_SUPER_USER=Admin
      - AGRAPH_SUPER_PASSWORD=KbA8KuX3E7aZSOVwGCxiK4
        networks:
      - app_network


  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge